### ISSUE TITLE
Sun Glare Overlay

### ISSUE THREAD

**Issue by bcrotty** [Whitebrim/Minimap#1]
When I have Minimap running and I look at the sun, it overlays some sun glare that persists even when I look away from the sun. As I continue to look around, there are light shafts that stay in the middle of the screen no matter where I look.

I'm not sure if it's related, but I turned my FOV up.

**Comment by Whitebrim** [comment]
https://github.com/Whitebrim/Minimap/releases/tag/v1.2.0
